<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerEqq3uuo\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerEqq3uuo/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerEqq3uuo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerEqq3uuo\appDevDebugProjectContainer();
